name: Sync to HuggingFace Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKENG }}
        run: |
          git config --global user.email "dharnilotpal31@gmail.com"
          git config --global user.name "nilotpaldhar2004"

          # Add HuggingFace remote using explicit username
          git remote add hf https://nilotpaldhar2004:$HF_TOKEN@huggingface.co/spaces/nilotpaldhar2004/fingerprint-blood-group

          # Force push to HF
          git push hf main --force
